#!/bin/sh

# Arguments
c1=$1  # Environment
c2=$2  # Command
c3=$3  # Command argument (optional)


# Help command
help() {
  echo "Usage: <environment> <command> [<command argument>]"
  echo "environment:"
  echo "* local"
  echo "* production"
  echo ""
  echo "command:"
  echo "* generate_ssl_certificates -- generate local https certificate to test functionality that requires it"
  echo "* build -- build the docker image"
  echo "* init -- build, generate_ssl_certificates, git init, pre-commit install"
  echo "* up -- start the docker container"
  echo "* down -- stop the docker container"
  echo "* shell -- open Django shell"
  echo "* showmigrations -- show all migrations of the project"
  echo "* makemigrations -- create migration files based on model changes"
  echo "* migrate -- migrate the migration file changes into the database"
  echo "* createsuperuser -- create superadmin user"
  echo "* startapp [APP_NAME] -- create a new app"
  echo "* backup_db -- create a database backup locally"
  echo "* list_backup_db -- list the local database backups"
  echo "* restore_db [BACKUP_FILE] -- restore the local database from a backup"
  echo "* upload_backup_db_s3 -- upload a database backup file to S3"
  echo "* download_backup_db_s3 [BACKUP_FILE] -- download a specific database backup from S3"
  echo "* ruff -- test ruff formatting"
  echo "* format -- format code with ruff"
  echo "* pytest -- run all tests"
  echo "* coverage -- run all tests and print coverage information"
  echo "* mypy -- check python typings"
  echo "* check_all -- check tests, types and formatting"
}


# App commands
generate_ssl_certificates() {
  if [ "$c1" = "local" ]
  then
    mkdir certs && docker compose -f "$c1".yml run django openssl req -newkey rsa:4096 -x509 -sha256 -days 3650 -nodes -out certs/my-dev-env.local.crt -keyout certs/my-dev-env.local.key -subj "/CN=my-dev-env.local" && echo "Certificates generated successfully."
  else
    echo "Operation aborted. Certificates can only be generated for 'local' environment."
  fi
}

build() {
  docker compose -f "$c1".yml build
}

init() {
  echo "Do you confirm that the following are installed: docker, docker compose, git, openssl and pre-commit (y/n)? "
  read -r answer
  if [ "$answer" = "y" ]
  then
    build
    generate_ssl_certificates
    git init
    pre-commit install
  else
    echo "Operation aborted. Please install docker, docker compose, git, openssl and pre-commit."
  fi
}

up() {
  docker compose -f "$c1".yml up
}

down() {
  docker compose -f "$c1".yml down
}


# Django commands
shell() {
  docker compose -f "$c1".yml run --rm django python manage.py shell
}

showmigrations() {
  docker compose -f "$c1".yml run --rm django python manage.py showmigrations
}

makemigrations() {
  docker compose -f "$c1".yml run --rm django python manage.py makemigrations
}

migrate() {
  docker compose -f "$c1".yml run --rm django python manage.py migrate
}

createsuperuser() {
  docker compose -f "$c1".yml run --rm django python manage.py createsuperuser
}

startapp() {
  docker compose -f local.yml run --rm django python manage.py startapp --template=./template_app "$c3"
  mv ./"$c3" ./api/"$c3"
}


# Postgres commands
backup_db() {
  docker compose -f local.yml exec postgres backup
  docker cp "$(docker compose -f local.yml ps -q postgres)":/backups ./backups
}

list_backup_db() {
  docker compose -f local.yml exec postgres backups
}

restore_db() {
  docker compose -f local.yml exec postgres restore "$c3"
}

upload_backup_db_s3() {
  docker compose -f production.yml run --rm awscli upload
}

download_backup_db_s3() {
  docker compose -f production.yml run --rm awscli download "$c3"
}


# Code check commands
ruff() {
  echo "RUFF" && docker compose -f "$c1".yml run --rm django ruff check
}

format() {
  echo "RUFF" && docker compose -f "$c1".yml run --rm django ruff format
}

mypy() {
  echo "MYPY" && docker compose -f local.yml run --rm django mypy api
}

pytest() {
  echo "PYTEST" && docker compose -f "$c1".yml run --rm django pytest
}

coverage() {
  docker compose -f local.yml run --rm django coverage run -m pytest
  docker compose -f local.yml run --rm django coverage report
}

check_all() {
  ruff && echo "ruff - No issue found"
  # mypy && echo "mypy - No issue found"
  coverage && echo "coverage - No issue found"
  # unittest && echo "unittest - No issue found"
}

case "$c1" in
  "local"|"production")
    $c2;;
  *)
    help;;
esac
